// app
export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_MESSAGE = 'SET_LOADING_MESSAGE';

// sun-position
export const SET_SUN_POSITION = 'SET_SUN_POSITION';
export const SET_SUN_POSITION_LOADED = 'SET_SUN_POSITION_LOADED';
export const SET_SUN_POSITION_UPDATED_AT = 'SET_SUN_POSITION_UPDATED_AT';

// locations
export const ADD_DEFAULT_LOCATION = 'ADD_DEFAULT_LOCATION';
export const SET_LOCATIONS_LOADED = 'SET_LOCATIONS_LOADED';
export const ADD_LOCATION = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const SET_DEFAULT_LOCATION = 'SET_DEFAULT_LOCATION';

// current-weather
export const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER';
export const SET_CURRENT_WEATHER_LOADED = 'SET_CURRENT_WEATHER_LOADED';
export const SET_CURRENT_WEATHER_UPDATED_AT = 'SET_CURRENT_WEATHER_UPDATED_AT';

// weather-alerts
export const SET_WEATHER_ALERTS = 'SET_WEATHER_ALERTS';
export const SET_WEATHER_ALERTS_LOADED = 'SET_WEATHER_ALERTS_LOADED';
export const SET_WEATHER_ALERTS_UPDATED_AT = 'SET_WEATHER_ALERTS_UPDATED_AT';

// hourly-weather
export const SET_HOURLY_WEATHER = 'SET_HOURLY_WEATHER';
export const SET_HOURLY_WEATHER_LOADED = 'SET_HOURLY_WEATHER_LOADED';
export const SET_HOURLY_WEATHER_UPDATED_AT = 'SET_HOURLY_WEATHER_UPDATED_AT';

// daily-weather
export const SET_DAILY_WEATHER = 'SET_DAILY_WEATHER';
export const SET_DAILY_WEATHER_LOADED = 'SET_DAILY_WEATHER_LOADED';
export const SET_DAILY_WEATHER_UPDATED_AT = 'SET_DAILY_WEATHER_UPDATED_AT';

// minutely-weather
export const SET_MINUTELY_WEATHER = 'SET_MINUTELY_WEATHER';
export const SET_MINUTELY_WEATHER_LOADED = 'SET_MINUTELY_WEATHER_LOADED';
export const SET_MINUTELY_WEATHER_UPDATED_AT = 'SET_MINUTELY_WEATHER_UPDATED_AT';
